/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CardDataDTO { 
    license?: any | null;
    tags?: Array<string>;
    library_name?: string;
    pipeline_tag?: string;
}

