/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceHFModelDTO } from './sourceHFModelDTO';


export interface HFModelDTO { 
    id?: string;
    huggingFaceLastFetchTimestampMs?: number;
    huggingFaceInfo?: SourceHFModelDTO;
    extra?: { [key: string]: any | null; };
}

