/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HuggingFaceSynchronizationStateDTO { 
    fullScanNextUrl?: string;
    fullScanComplete?: boolean;
    incrementalNextUrl?: string;
    lastSyncThreshold?: string;
    newestSeenThisRun?: string;
    totalModelsSynced?: number;
    lastRunErrors?: number;
}

