/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LfsDTO } from './lfsDTO';


export interface SiblingDTO { 
    rfilename?: string;
    blobId?: string;
    size?: number;
    lfs?: LfsDTO;
}

