/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SafetensorsDTO } from './safetensorsDTO';
import { SiblingDTO } from './siblingDTO';
import { TransformersInfoDTO } from './transformersInfoDTO';
import { CardDataDTO } from './cardDataDTO';


export interface SourceHFModelDTO { 
    _id?: string;
    id?: string;
    tags?: Array<string>;
    downloads?: number;
    likes?: number;
    modelId?: string;
    author?: string;
    sha?: string;
    lastModified?: string;
    gated?: string;
    disabled?: boolean;
    widgetData?: Array<{ [key: string]: any | null; }>;
    config?: { [key: string]: any | null; };
    cardData?: CardDataDTO;
    transformersInfo?: TransformersInfoDTO;
    siblings?: Array<SiblingDTO>;
    spaces?: Array<string>;
    createdAt?: string;
    safetensors?: SafetensorsDTO;
    usedStorage?: number;
    'private'?: boolean;
    pipeline_tag?: string;
    library_name?: string;
    'model-index'?: any | null;
}

